const VALID_INDUSTRIES = [
  'Distributor',
  'Food & Beverage',
  'Insurance & Benefits',
  'Manufacturer',
  'Medical',
  'Pharmaceutical',
  'Professional Services',
  'Rep Agency',
  'Equipment Rental',
  'Other Industry',
];

const COUNTRY_CODES_MAP = {
  au: '+61',
  at: '+43',
  be: '+32',
  bz: '+501',
  br: '+55',
  bg: '+359',
  ca: '+1',
  co: '+57',
  cr: '+506',
  hr: '+385',
  cy: '+357',
  cz: '+420',
  dk: '+45',
  eg: '+20',
  sv: '+503',
  ee: '+372',
  fi: '+358',
  fr: '+33',
  de: '+49',
  gr: '+30',
  gl: '+299',
  gt: '+502',
  hn: '+504',
  hu: '+36',
  is: '+354',
  in: '+91',
  ie: '+353',
  it: '+39',
  lv: '+371',
  li: '+423',
  lt: '+370',
  lu: '+352',
  mt: '+356',
  mx: '+52',
  mc: '+377',
  nl: '+31',
  nz: '+64',
  ni: '+505',
  no: '+47',
  pk: '+92',
  pa: '+507',
  pl: '+48',
  pt: '+351',
  pr: '+1',
  ro: '+40',
  sm: '+378',
  sk: '+421',
  si: '+386',
  za: '+27',
  es: '+34',
  se: '+46',
  ch: '+41',
  ua: '+380',
  gb: '+44',
  us: '+1',
};

const COUNTRY_LOCALE_MAP: Record<string, string> = {
  au: 'en_AU',
  at: 'de_AT',
  be: 'fr_BE',
  br: 'pt_BR',
  ca: 'en_CA',
  cz: 'cs_CZ',
  dk: 'da',
  fr: 'fr',
  de: 'de',
  hu: 'hu',
  in: 'en_IN',
  ie: 'en_IE',
  it: 'it',
  mx: 'es_MX',
  nl: 'nl',
  no: 'nb_NO',
  pl: 'pl',
  pt: 'pt_PT',
  ro: 'ro',
  sk: 'sk',
  za: 'en_ZA',
  es: 'es',
  se: 'sv',
  ch: 'de_CH',
  ua: 'uk',
  gb: 'en_GB',
};

export const constants = {
  VALID_INDUSTRIES,
  COUNTRY_CODES_MAP,
  COUNTRY_LOCALE_MAP,
};
